const mongoose = require ('mongoose')

const Schema = mongoose.Schema

const profileSchema = new Schema ({
    user:{
        type:Schema.Types.ObjectId,
        ref:'User'
    },
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true
    },
    company:{
        type:String
    },
    bio:{
        type:String
    },
    website:{
        type:String
    },
    location:{
        type:String
    },
    social:{
        linkedin:{
            type:String
        },
        twitter:{
            type:String
        },
        facebook:{
            type:String
        }
    },
    experience:[
        {
            company:{
                type:String,
                required:true
            },
            title:{
                type:String,
                required:true
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:Date
            },
            current:{
                type:Boolean,
                default:false
            },
            description:{
                type:String
            },
            location:{
                type:String
            }
        }
    ],
    education:[
        {
            school:{
                type:String,
                required:true
            },
            fieldOfStudy:{
                type:String,
                required:true
            },
            degree:{
                type:String,
                required:true
            },
            from:{
                type:Date,
                required:true
            },
            to:{
                type:Date
            },
            current:{
                type:Boolean,
                default:false
            },
            description:{
                type:String
            }
        }
    ],
    date:{
        type:Date,
        default:Date.now
    }
})

module.exports = mongoose.model('Profile', profileSchema)